/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mp32;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author User
 */
public class LeitorBancoVht {
    //Leitor banco de dados
    Conexao c = new Conexao();
    Connection con = c.Conectar();
    Statement stm;
    ResultSet rs;
    
    String dir = "select * from SONGLIST where (SONGTYPE) = 'X'";
    String title = "select * from SONGLIST where (SONGTYPE) = 'X'";
    
    String intro = new String();
    String Aba1 = new String();
    String a1l1 = new String();
    String a1l2 = new String();
    String a1l3 = new String();
    String a1l4 = new String();
    String a1l5 = new String();
    String a1l6 = new String();
    String a1l7 = new String();
    String a1l8 = new String();
    String a1l9 = new String();
    String a1l10 = new String();
    String a1l11 = new String();
    String a1l12= new String();
    String a1l13 = new String();
    String a1l14 = new String();
    String a1l15 = new String();
    String a1l16 = new String();
    
    String Aba2 = new String();
    String a2l1 = new String();
    String a2l2 = new String();
    String a2l3 = new String();
    String a2l4 = new String();
    String a2l5 = new String();
    String a2l6 = new String();
    String a2l7 = new String();
    String a2l8 = new String();
    String a2l9 = new String();
    String a2l10 = new String();
    String a2l11 = new String();
    String a2l12= new String();
    String a2l13 = new String();
    String a2l14 = new String();
    String a2l15 = new String();
    String a2l16 = new String();
    
    
    String Aba3 = new String();
    String a3l1 = new String();
    String a3l2 = new String();
    String a3l3 = new String();
    String a3l4 = new String();
    String a3l5 = new String();
    String a3l6 = new String();
    String a3l7 = new String();
    String a3l8 = new String();
    String a3l9 = new String();
    String a3l10 = new String();
    String a3l11 = new String();
    String a3l12= new String();
    String a3l13 = new String();
    String a3l14 = new String();
    String a3l15 = new String();
    String a3l16 = new String();
    
    
    String Aba4 = new String();
    String a4l1 = new String();
    String a4l2 = new String();
    String a4l3 = new String();
    String a4l4 = new String();
    String a4l5 = new String();
    String a4l6 = new String();
    String a4l7 = new String();
    String a4l8 = new String();
    String a4l9 = new String();
    String a4l10 = new String();
    String a4l11 = new String();
    String a4l12= new String();
    String a4l13 = new String();
    String a4l14 = new String();
    String a4l15 = new String();
    String a4l16 = new String();
    
    
    String Aba5 = new String();
    String a5l1 = new String();
    String a5l2 = new String();
    String a5l3 = new String();
    String a5l4 = new String();
    String a5l5 = new String();
    String a5l6 = new String();
    String a5l7 = new String();
    String a5l8 = new String();
    String a5l9 = new String();
    String a5l10 = new String();
    String a5l11 = new String();
    String a5l12= new String();
    String a5l13 = new String();
    String a5l14 = new String();
    String a5l15 = new String();
    String a5l16 = new String();
    
    
    String Aba6 = new String();
    String a6l1 = new String();
    String a6l2 = new String();
    String a6l3 = new String();
    String a6l4 = new String();
    String a6l5 = new String();
    String a6l6 = new String();
    String a6l7 = new String();
    String a6l8 = new String();
    String a6l9 = new String();
    String a6l10 = new String();
    String a6l11 = new String();
    String a6l12= new String();
    String a6l13 = new String();
    String a6l14 = new String();
    String a6l15 = new String();
    String a6l16 = new String();
    
    String Aba7 = new String();
    String a7l1 = new String();
    String a7l2 = new String();
    String a7l3 = new String();
    String a7l4 = new String();
    String a7l5 = new String();
    String a7l6 = new String();
    String a7l7 = new String();
    String a7l8 = new String();
    String a7l9 = new String();
    String a7l10 = new String();
    String a7l11 = new String();
    String a7l12= new String();
    String a7l13 = new String();
    String a7l14 = new String();
    String a7l15 = new String();
    String a7l16 = new String();
    
    String Aba8 = new String();
    String a8l1 = new String();
    String a8l2 = new String();
    String a8l3 = new String();
    String a8l4 = new String();
    String a8l5 = new String();
    String a8l6 = new String();
    String a8l7 = new String();
    String a8l8 = new String();
    String a8l9 = new String();
    String a8l10 = new String();
    String a8l11 = new String();
    String a8l12= new String();
    String a8l13 = new String();
    String a8l14 = new String();
    String a8l15 = new String();
    String a8l16 = new String();
    
    String Aba9 = new String();
    String a9l1 = new String();
    String a9l2 = new String();
    String a9l3 = new String();
    String a9l4 = new String();
    String a9l5 = new String();
    String a9l6 = new String();
    String a9l7 = new String();
    String a9l8 = new String();
    String a9l9 = new String();
    String a9l10 = new String();
    String a9l11 = new String();
    String a9l12= new String();
    String a9l13 = new String();
    String a9l14 = new String();
    String a9l15 = new String();
    String a9l16 = new String();
   
    String Aba10 = new String();
    String a10l1 = new String();
    String a10l2 = new String();
    String a10l3 = new String();
    String a10l4 = new String();
    String a10l5 = new String();
    String a10l6 = new String();
    String a10l7 = new String();
    String a10l8 = new String();
    String a10l9 = new String();
    String a10l10 = new String();
    String a10l11 = new String();
    String a10l12= new String();
    String a10l13 = new String();
    String a10l14 = new String();
    String a10l15 = new String();
    String a10l16 = new String();
    

    String a1t1 = new String();
    String a1t2 = new String();
    String a1t3 = new String();
    String a1t4 = new String();
    String a1t5 = new String();
    String a1t6 = new String();
    String a1t7 = new String();
    String a1t8 = new String();
    String a1t9 = new String();
    String a1t10 = new String();
    String a1t11 = new String();
    String a1t12= new String();
    String a1t13 = new String();
    String a1t14 = new String();
    String a1t15 = new String();
    String a1t16 = new String();
    
    String a2t1 = new String();
    String a2t2 = new String();
    String a2t3 = new String();
    String a2t4 = new String();
    String a2t5 = new String();
    String a2t6 = new String();
    String a2t7 = new String();
    String a2t8 = new String();
    String a2t9 = new String();
    String a2t10 = new String();
    String a2t11 = new String();
    String a2t12= new String();
    String a2t13 = new String();
    String a2t14 = new String();
    String a2t15 = new String();
    String a2t16 = new String();
    
    
    String a3t1 = new String();
    String a3t2 = new String();
    String a3t3 = new String();
    String a3t4 = new String();
    String a3t5 = new String();
    String a3t6 = new String();
    String a3t7 = new String();
    String a3t8 = new String();
    String a3t9 = new String();
    String a3t10 = new String();
    String a3t11 = new String();
    String a3t12= new String();
    String a3t13 = new String();
    String a3t14 = new String();
    String a3t15 = new String();
    String a3t16 = new String();
    
    
    String a4t1 = new String();
    String a4t2 = new String();
    String a4t3 = new String();
    String a4t4 = new String();
    String a4t5 = new String();
    String a4t6 = new String();
    String a4t7 = new String();
    String a4t8 = new String();
    String a4t9 = new String();
    String a4t10 = new String();
    String a4t11 = new String();
    String a4t12= new String();
    String a4t13 = new String();
    String a4t14 = new String();
    String a4t15 = new String();
    String a4t16 = new String();
    
    
    String a5t1 = new String();
    String a5t2 = new String();
    String a5t3 = new String();
    String a5t4 = new String();
    String a5t5 = new String();
    String a5t6 = new String();
    String a5t7 = new String();
    String a5t8 = new String();
    String a5t9 = new String();
    String a5t10 = new String();
    String a5t11 = new String();
    String a5t12= new String();
    String a5t13 = new String();
    String a5t14 = new String();
    String a5t15 = new String();
    String a5t16 = new String();
    
    
    String a6t1 = new String();
    String a6t2 = new String();
    String a6t3 = new String();
    String a6t4 = new String();
    String a6t5 = new String();
    String a6t6 = new String();
    String a6t7 = new String();
    String a6t8 = new String();
    String a6t9 = new String();
    String a6t10 = new String();
    String a6t11 = new String();
    String a6t12= new String();
    String a6t13 = new String();
    String a6t14 = new String();
    String a6t15 = new String();
    String a6t16 = new String();
    
    String a7t1 = new String();
    String a7t2 = new String();
    String a7t3 = new String();
    String a7t4 = new String();
    String a7t5 = new String();
    String a7t6 = new String();
    String a7t7 = new String();
    String a7t8 = new String();
    String a7t9 = new String();
    String a7t10 = new String();
    String a7t11 = new String();
    String a7t12= new String();
    String a7t13 = new String();
    String a7t14 = new String();
    String a7t15 = new String();
    String a7t16 = new String();
    
    String a8t1 = new String();
    String a8t2 = new String();
    String a8t3 = new String();
    String a8t4 = new String();
    String a8t5 = new String();
    String a8t6 = new String();
    String a8t7 = new String();
    String a8t8 = new String();
    String a8t9 = new String();
    String a8t10 = new String();
    String a8t11 = new String();
    String a8t12= new String();
    String a8t13 = new String();
    String a8t14 = new String();
    String a8t15 = new String();
    String a8t16 = new String();
    
    String a9t1 = new String();
    String a9t2 = new String();
    String a9t3 = new String();
    String a9t4 = new String();
    String a9t5 = new String();
    String a9t6 = new String();
    String a9t7 = new String();
    String a9t8 = new String();
    String a9t9 = new String();
    String a9t10 = new String();
    String a9t11 = new String();
    String a9t12= new String();
    String a9t13 = new String();
    String a9t14 = new String();
    String a9t15 = new String();
    String a9t16 = new String();
   
    String a10t1 = new String();
    String a10t2 = new String();
    String a10t3 = new String();
    String a10t4 = new String();
    String a10t5 = new String();
    String a10t6 = new String();
    String a10t7 = new String();
    String a10t8 = new String();
    String a10t9 = new String();
    String a10t10 = new String();
    String a10t11 = new String();
    String a10t12= new String();
    String a10t13 = new String();
    String a10t14 = new String();
    String a10t15 = new String();
    String a10t16 = new String();

    public void LerBanco(){   
        try{
            stm = con.createStatement();
            rs = stm.executeQuery(dir);
            
            //Aba 1
            rs.next();            
            a1l1 = rs.getString("FILENAME");
            a1t1 = rs.getString("TITLE");
            rs.next();            
            a1l2 = rs.getString("FILENAME");
            a1t2 = rs.getString("TITLE");
            rs.next();            
            a1l3 = rs.getString("FILENAME");
            a1t3 = rs.getString("TITLE");
            rs.next();            
            a1l4 = rs.getString("FILENAME");
            a1t4 = rs.getString("TITLE");
            rs.next();            
            a1l5 = rs.getString("FILENAME");
            a1t5 = rs.getString("TITLE");
            rs.next();            
            a1l6 = rs.getString("FILENAME");
            a1t6 = rs.getString("TITLE");
            rs.next();            
            a1l7 = rs.getString("FILENAME");
            a1t7 = rs.getString("TITLE");
            rs.next();            
            a1l8 = rs.getString("FILENAME");
            a1t8 = rs.getString("TITLE");
            rs.next();            
            a1l9 = rs.getString("FILENAME");
            a1t9 = rs.getString("TITLE");
            rs.next();            
            a1l10 = rs.getString("FILENAME");
            a1t10 = rs.getString("TITLE");
            rs.next();            
            a1l11 = rs.getString("FILENAME");
            a1t11 = rs.getString("TITLE");
            rs.next();            
            a1l12 = rs.getString("FILENAME");
            a1t12 = rs.getString("TITLE");
            rs.next();            
            a1l13 = rs.getString("FILENAME");
            a1t13 = rs.getString("TITLE");
            rs.next();            
            a1l14 = rs.getString("FILENAME");
            a1t14 = rs.getString("TITLE");
            rs.next();            
            a1l15 = rs.getString("FILENAME");
            a1t15 = rs.getString("TITLE");
            rs.next();            
            a1l16 = rs.getString("FILENAME");
            a1t16 = rs.getString("TITLE");
//Aba 2
            rs.next();            
            a2l1 = rs.getString("FILENAME");
            a2t1 = rs.getString("TITLE");
            rs.next();            
            a2l2 = rs.getString("FILENAME");
            a2t2 = rs.getString("TITLE");
            rs.next();            
            a2l3 = rs.getString("FILENAME");
            a2t3 = rs.getString("TITLE");
            rs.next();            
            a2l4 = rs.getString("FILENAME");
            a2t4 = rs.getString("TITLE");
            rs.next();            
            a2l5 = rs.getString("FILENAME");
            a2t5 = rs.getString("TITLE");
            rs.next();            
            a2l6 = rs.getString("FILENAME");
            a2t1 = rs.getString("TITLE");
            rs.next();            
            a2l7 = rs.getString("FILENAME");
            a2t7 = rs.getString("TITLE");
            rs.next();            
            a2l8 = rs.getString("FILENAME");
            a2t8 = rs.getString("TITLE");
            rs.next();            
            a2l9 = rs.getString("FILENAME");
            a2t9 = rs.getString("TITLE");
            rs.next();            
            a2l10 = rs.getString("FILENAME");
            a2t10 = rs.getString("TITLE");
            rs.next();            
            a2l11 = rs.getString("FILENAME");
            a2t11 = rs.getString("TITLE");
            rs.next();            
            a2l12 = rs.getString("FILENAME");
            a2t12 = rs.getString("TITLE");
            rs.next();            
            a2l13 = rs.getString("FILENAME");
            a2t13 = rs.getString("TITLE");
            rs.next();            
            a2l14 = rs.getString("FILENAME");
            a2t14 = rs.getString("TITLE");
            rs.next();            
            a2l15 = rs.getString("FILENAME");
            a2t15 = rs.getString("TITLE");
            rs.next();            
            a2l16 = rs.getString("FILENAME");
            a2t16 = rs.getString("TITLE");
            

//Aba 3
            rs.next();            
            a3l1 = rs.getString("FILENAME");
            a3t1 = rs.getString("TITLE");
            rs.next();            
            a3l2 = rs.getString("FILENAME");
            a3t2 = rs.getString("TITLE");
            rs.next();            
            a3l3 = rs.getString("FILENAME");
            a3t3 = rs.getString("TITLE");
            rs.next();            
            a3l4 = rs.getString("FILENAME");
            a3t4 = rs.getString("TITLE");
            rs.next();            
            a3l5 = rs.getString("FILENAME");
            a3t5 = rs.getString("TITLE");
            rs.next();            
            a3l6 = rs.getString("FILENAME");
            a3t6 = rs.getString("TITLE");
            rs.next();            
            a3l7 = rs.getString("FILENAME");
            a3t7 = rs.getString("TITLE");
            rs.next();            
            a3l8 = rs.getString("FILENAME");
            a3t8 = rs.getString("TITLE");
            rs.next();            
            a3l9 = rs.getString("FILENAME");
            a3t9 = rs.getString("TITLE");
            rs.next();            
            a3l10 = rs.getString("FILENAME");
            a3t10 = rs.getString("TITLE");
            rs.next();            
            a3l11 = rs.getString("FILENAME");
            a3t11 = rs.getString("TITLE");
            rs.next();            
            a3l12 = rs.getString("FILENAME");
            a3t12 = rs.getString("TITLE");
            rs.next();            
            a3l13 = rs.getString("FILENAME");
            a3t13 = rs.getString("TITLE");
            rs.next();            
            a3l14 = rs.getString("FILENAME");
            a3t14 = rs.getString("TITLE");
            rs.next();            
            a3l15 = rs.getString("FILENAME");
            a3t15 = rs.getString("TITLE");
            rs.next();            
            a3l16 = rs.getString("FILENAME");
            a3t16 = rs.getString("TITLE");

//Aba 4
            rs.next();            
            a4l1 = rs.getString("FILENAME");
            a4t1 = rs.getString("TITLE");
            rs.next();            
            a4l2 = rs.getString("FILENAME");
            a4t2 = rs.getString("TITLE");
            rs.next();            
            a4l3 = rs.getString("FILENAME");
            a4t3 = rs.getString("TITLE");
            rs.next();            
            a4l4 = rs.getString("FILENAME");
            a4t4 = rs.getString("TITLE");
            rs.next();            
            a4l5 = rs.getString("FILENAME");
            a4t5 = rs.getString("TITLE");
            rs.next();            
            a4l6 = rs.getString("FILENAME");
            a4t6 = rs.getString("TITLE");
            rs.next();            
            a4l7 = rs.getString("FILENAME");
            a4t7 = rs.getString("TITLE");
            rs.next();            
            a4l8 = rs.getString("FILENAME");
            a4t8 = rs.getString("TITLE");
            rs.next();            
            a4l9 = rs.getString("FILENAME");
            a4t9 = rs.getString("TITLE");
            rs.next();            
            a4l10 = rs.getString("FILENAME");
            a4t10 = rs.getString("TITLE");
            rs.next();            
            a4l11 = rs.getString("FILENAME");
            a4t11 = rs.getString("TITLE");
            rs.next();            
            a4l12 = rs.getString("FILENAME");
            a4t12 = rs.getString("TITLE");
            rs.next();            
            a4l13 = rs.getString("FILENAME");
            a4t13 = rs.getString("TITLE");
            rs.next();            
            a4l14 = rs.getString("FILENAME");
            a4t14 = rs.getString("TITLE");
            rs.next();            
            a4l15 = rs.getString("FILENAME");
            a4t15 = rs.getString("TITLE");
            rs.next();            
            a4l16 = rs.getString("FILENAME");
            a4t16 = rs.getString("TITLE");
            
            //Aba 5
            rs.next();            
            a5l1 = rs.getString("FILENAME");
            a5t1 = rs.getString("TITLE");
            rs.next();            
            a5l2 = rs.getString("FILENAME");
            a5t2 = rs.getString("TITLE");
            rs.next();            
            a5l3 = rs.getString("FILENAME");
            a5t3 = rs.getString("TITLE");
            rs.next();            
            a5l4 = rs.getString("FILENAME");
            a5t4 = rs.getString("TITLE");
            rs.next();            
            a5l5 = rs.getString("FILENAME");
            a5t5 = rs.getString("TITLE");
            rs.next();            
            a5l6 = rs.getString("FILENAME");
            a5t6 = rs.getString("TITLE");
            rs.next();            
            a5l7 = rs.getString("FILENAME");
            a5t7 = rs.getString("TITLE");
            rs.next();            
            a5l8 = rs.getString("FILENAME");
            a5t8 = rs.getString("TITLE");
            rs.next();            
            a5l9 = rs.getString("FILENAME");
            a5t9 = rs.getString("TITLE");
            rs.next();            
            a5l10 = rs.getString("FILENAME");
            a5t10 = rs.getString("TITLE");
            rs.next();            
            a5l11 = rs.getString("FILENAME");
            a5t11 = rs.getString("TITLE");
            rs.next();            
            a5l12 = rs.getString("FILENAME");
            a5t12 = rs.getString("TITLE");
            rs.next();            
            a5l13 = rs.getString("FILENAME");
            a5t13 = rs.getString("TITLE");
            rs.next();            
            a5l14 = rs.getString("FILENAME");
            a5t14 = rs.getString("TITLE");
            rs.next();            
            a5l15 = rs.getString("FILENAME");
            a5t15 = rs.getString("TITLE");
            rs.next();
            a5l16 = rs.getString("FILENAME");
            a5t16 = rs.getString("TITLE");
            
                        //Aba 6
            rs.next();            
            a6l1 = rs.getString("FILENAME");
            a6t1 = rs.getString("TITLE");
            rs.next();            
            a6l2 = rs.getString("FILENAME");
            a6t2 = rs.getString("TITLE");
            rs.next();            
            a6l3 = rs.getString("FILENAME");
            a6t3 = rs.getString("TITLE");
            rs.next();            
            a6l4 = rs.getString("FILENAME");
            a6t4 = rs.getString("TITLE");
            rs.next();            
            a6l5 = rs.getString("FILENAME");
            a6t5 = rs.getString("TITLE");
            rs.next();            
            a6l6 = rs.getString("FILENAME");
            a6t6 = rs.getString("TITLE");
            rs.next();            
            a6l7 = rs.getString("FILENAME");
            a6t7 = rs.getString("TITLE");
            rs.next();            
            a6l8 = rs.getString("FILENAME");
            a6t8 = rs.getString("TITLE");
            rs.next();            
            a6l9 = rs.getString("FILENAME");
            a6t9 = rs.getString("TITLE");
            rs.next();            
            a6l10 = rs.getString("FILENAME");
            a6t10 = rs.getString("TITLE");
            rs.next();            
            a6l11 = rs.getString("FILENAME");
            a6t11 = rs.getString("TITLE");
            rs.next();            
            a6l12 = rs.getString("FILENAME");
            a6t12 = rs.getString("TITLE");
            rs.next();            
            a6l13 = rs.getString("FILENAME");
            a6t13 = rs.getString("TITLE");
            rs.next();            
            a6l14 = rs.getString("FILENAME");
            a6t14 = rs.getString("TITLE");
            rs.next();            
            a6l15 = rs.getString("FILENAME");
            a6t15 = rs.getString("TITLE");
            rs.next();            
            a6l16 = rs.getString("FILENAME");
            a6t16 = rs.getString("TITLE");
            
                        //Aba 7
            rs.next();            
            a7l1 = rs.getString("FILENAME");
            a7t1 = rs.getString("TITLE");
            rs.next();            
            a7l2 = rs.getString("FILENAME");
            a7t2 = rs.getString("TITLE");
            rs.next();            
            a7l3 = rs.getString("FILENAME");
            a7t3 = rs.getString("TITLE");
            rs.next();            
            a7l4 = rs.getString("FILENAME");
            a7t4 = rs.getString("TITLE");
            rs.next();            
            a7l5 = rs.getString("FILENAME");
            a7t5 = rs.getString("TITLE");
            rs.next();            
            a7l6 = rs.getString("FILENAME");
            a7t6 = rs.getString("TITLE");
            rs.next();            
            a7l7 = rs.getString("FILENAME");
            a7t7 = rs.getString("TITLE");
            rs.next();
            a7l8 = rs.getString("FILENAME");
            a7t8 = rs.getString("TITLE");
            rs.next();            
            a7l9 = rs.getString("FILENAME");
            a7t9 = rs.getString("TITLE");
            rs.next();            
            a7l10 = rs.getString("FILENAME");
            a7t10 = rs.getString("TITLE");
            rs.next();            
            a7l11 = rs.getString("FILENAME");
            a7t11 = rs.getString("TITLE");
            rs.next();            
            a7l12 = rs.getString("FILENAME");
            a7t12 = rs.getString("TITLE");
            rs.next();            
            a7l13 = rs.getString("FILENAME");
            a7t13 = rs.getString("TITLE");
            rs.next();            
            a7l14 = rs.getString("FILENAME");
            a7t14 = rs.getString("TITLE");
            rs.next();            
            a7l15 = rs.getString("FILENAME");
            a7t15 = rs.getString("TITLE");
            rs.next();            
            a7l16 = rs.getString("FILENAME");
            a7t16 = rs.getString("TITLE");
            
                        //Aba 8
            rs.next();            
            a8l1 = rs.getString("FILENAME");
            a8t1 = rs.getString("TITLE");
            rs.next();            
            a8l2 = rs.getString("FILENAME");
            a8t2 = rs.getString("TITLE");
            rs.next();            
            a8l3 = rs.getString("FILENAME");
            a8t3 = rs.getString("TITLE");
            rs.next();            
            a8l4 = rs.getString("FILENAME");
            a8t4 = rs.getString("TITLE");
            rs.next();            
            a8l5 = rs.getString("FILENAME");
            a8t5 = rs.getString("TITLE");
            rs.next();            
            a8l6 = rs.getString("FILENAME");
            a8t6 = rs.getString("TITLE");
            rs.next();            
            a8l7 = rs.getString("FILENAME");
            a8t7 = rs.getString("TITLE");
            rs.next();            
            a8l8 = rs.getString("FILENAME");
            a8t8 = rs.getString("TITLE");
            rs.next();            
            a8l9 = rs.getString("FILENAME");
            a8t9 = rs.getString("TITLE");
            rs.next();            
            a8l10 = rs.getString("FILENAME");
            a8t10 = rs.getString("TITLE");
            rs.next();            
            a8l11 = rs.getString("FILENAME");
            a8t11 = rs.getString("TITLE");
            rs.next();
            a8l12 = rs.getString("FILENAME");
            a8t12 = rs.getString("TITLE");
            rs.next();            
            a8l13 = rs.getString("FILENAME");
            a8t13 = rs.getString("TITLE");
            rs.next();            
            a8l14 = rs.getString("FILENAME");
            a8t14 = rs.getString("TITLE");
            rs.next();            
            a8l15 = rs.getString("FILENAME");
            a8t15 = rs.getString("TITLE");
            rs.next();            
            a8l16 = rs.getString("FILENAME");
            a8t16 = rs.getString("TITLE");
            
                        //Aba 9
            rs.next();            
            a9l1 = rs.getString("FILENAME");
            a9t1 = rs.getString("TITLE");
            rs.next();            
            a9l2 = rs.getString("FILENAME");
            a9t2 = rs.getString("TITLE");
            rs.next();            
            a9l3 = rs.getString("FILENAME");
            a9t3 = rs.getString("TITLE");
            rs.next();            
            a9l4 = rs.getString("FILENAME");
            a9t4 = rs.getString("TITLE");
            rs.next();            
            a9l5 = rs.getString("FILENAME");
            a9t5 = rs.getString("TITLE");
            rs.next();            
            a9l6 = rs.getString("FILENAME");
            a9t6 = rs.getString("TITLE");
            rs.next();            
            a9l7 = rs.getString("FILENAME");
            a9t7 = rs.getString("TITLE");
            rs.next();            
            a9l8 = rs.getString("FILENAME");
            a9t8 = rs.getString("TITLE");
            rs.next();            
            a9l9 = rs.getString("FILENAME");
            a9t9 = rs.getString("TITLE");
            rs.next();            
            a9l10 = rs.getString("FILENAME");
            a9t10 = rs.getString("TITLE");
            rs.next();            
            a9l11 = rs.getString("FILENAME");
            a9t11 = rs.getString("TITLE");
            rs.next();            
            a9l12 = rs.getString("FILENAME");
            a9t12 = rs.getString("TITLE");
            rs.next();            
            a9l13 = rs.getString("FILENAME");
            a9t13 = rs.getString("TITLE");
            rs.next();            
            a9l14 = rs.getString("FILENAME");
            a9t14 = rs.getString("TITLE");
            rs.next();            
            a9l15 = rs.getString("FILENAME");
            a9t15 = rs.getString("TITLE");
            rs.next();            
            a9l16 = rs.getString("FILENAME");
            a9t16 = rs.getString("TITLE");
            
                        //Aba 10
            rs.next();            
            a10l1 = rs.getString("FILENAME");
            a10t1 = rs.getString("TITLE");
            rs.next();            
            a10l2 = rs.getString("FILENAME");
            a10t2 = rs.getString("TITLE");
            rs.next();            
            a10l3 = rs.getString("FILENAME");
            a10t3 = rs.getString("TITLE");
            rs.next();            
            a10l4 = rs.getString("FILENAME");
            a10t4 = rs.getString("TITLE");
            rs.next();            
            a10l5 = rs.getString("FILENAME");
            a10t5 = rs.getString("TITLE");
            rs.next();            
            a10l6 = rs.getString("FILENAME");
            a10t6 = rs.getString("TITLE");
            rs.next();            
            a10l7 = rs.getString("FILENAME");
            a10t7 = rs.getString("TITLE");
            rs.next();            
            a10l8 = rs.getString("FILENAME");
            a10t8 = rs.getString("TITLE");
            rs.next();            
            a10l9 = rs.getString("FILENAME");
            a10t9 = rs.getString("TITLE");
            rs.next();            
            a10l10 = rs.getString("FILENAME");
            a10t10 = rs.getString("TITLE");
            rs.next();            
            a10l11 = rs.getString("FILENAME");
            a10t11 = rs.getString("TITLE");
            rs.next();            
            a10l12 = rs.getString("FILENAME");
            a10t12 = rs.getString("TITLE");
            rs.next();            
            a10l13 = rs.getString("FILENAME");
            a10t13 = rs.getString("TITLE");
            rs.next();            
            a10l14 = rs.getString("FILENAME");
            a10t14 = rs.getString("TITLE");
            rs.next();            
            a10l15 = rs.getString("FILENAME");
            a10t15 = rs.getString("TITLE");
            rs.next();            
            a10l16 = rs.getString("FILENAME");
            a10t16 = rs.getString("TITLE");
            
        }
        catch(SQLException e){
            
        }
    }
     
}
